In [1]:
import pymysql

In [2]:
db = pymysql.connect(host='localhost',user='root',password='52mahiru',port=3306,db='Apex')
cursor = db.cursor()
cursor.execute('drop table if exists Apex_Americas')
sql = 'create table if not exists Apex_Americas(Team varchar(255),ID varchar(255),Real_Name varchar(255),primary key(Team,ID,Real_Name))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_EMMA')
sql = 'create table if not exists Apex_EMMA(Team varchar(255),ID varchar(255),Real_Name varchar(255),primary key(Team,ID,Real_Name))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_APAC_North')
sql = 'create table if not exists Apex_APAC_North(Team varchar(255),ID varchar(255),Real_Name varchar(255),primary key(Team,ID,Real_Name))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_APAC_South')
sql = 'create table if not exists Apex_APAC_South(Team varchar(255),ID varchar(255),Real_Name varchar(255),primary key(Team,ID,Real_Name))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_Team')
sql = 'create table if not exists Apex_Team(Team varchar(255) primary key)'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_Player')
sql = 'create table if not exists Apex_Player(ID varchar(255),Real_Name varchar(255))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_Top20')
sql = 'create table if not exists Apex_Top20(ID varchar(255) primary key,Real_Name varchar(255),Country varchar(255),Born date Not NULL,Age int,Team varchar(255))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_NearlyMatch')
sql = 'create table if not exists Apex_NearlyMatch(ID varchar(255),Ranks varchar(255),Matches varchar(255))'
cursor.execute(sql)
for year in range(2019,2024):
    sqlT = 'drop table if exists Apex_Team'+str(year)
    sqlP = 'drop table if exists Apex_Player'+str(year)
    cursor.execute(sqlT)
    cursor.execute(sqlP)
    sqlT = 'create table if not exists Apex_Team'+str(year)+' (Team varchar(255),1st int,2nd int,3rd_4th int,Totalwinnings varchar(255))'
    sqlP = 'create table if not exists Apex_Player'+str(year)+' (ID varchar(255),1st int,2nd int,3rd_4th int,S_Tier int,Earnings varchar(255))'
    cursor.execute(sqlT)
    cursor.execute(sqlP)
cursor.execute('drop table if exists Apex_TeamOverall')
sql = 'create table if not exists Apex_TeamOverall(Team varchar(255),Totalwinnings varchar(255))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_PlayerOverall')
sql = 'create table if not exists Apex_PlayerOverall(ID varchar(255),1st int,2nd int,3rd_4th int,S_Tier int,Earnings varchar(255))'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_Youngest')
sql = 'create table if not exists Apex_Youngest(ID varchar(255),Age int)'
cursor.execute(sql)
cursor.execute('drop table if exists Apex_Oldest')
sql = 'create table if not exists Apex_Oldest(ID varchar(255),Age int)'
cursor.execute(sql)

#db.close()

0

In [3]:
import xlrd
import datetime
book = xlrd.open_workbook("(MySQL)Apex Legends Global Teams and Players.xlsx")
sheet1 = book.sheet_by_name("Americas")
sheet2 = book.sheet_by_name("EMMA")
sheet3 = book.sheet_by_name("APAC North")
sheet4 = book.sheet_by_name("APAC South")
sheet5 = book.sheet_by_name("Team")
sheet6 = book.sheet_by_name("Player")
sheet7 = book.sheet_by_name("Top20")
sheet8 = book.sheet_by_name("NearlyMatch")
sheet9 = book.sheet_by_name("2019-2023Team")
sheet10 = book.sheet_by_name("2019-2023Player")
sheet11 = book.sheet_by_name("TeamOverall")
sheet12 = book.sheet_by_name("PlayerOverall")
sheet13 = book.sheet_by_name("Youngest")
sheet14 = book.sheet_by_name("Oldest")

query1 = 'insert into Apex_Americas (Team,ID,Real_Name) values (%s,%s,%s)'
query2 = 'insert into Apex_EMMA (Team,ID,Real_Name) values (%s,%s,%s)'
query3 = 'insert into Apex_APAC_North (Team,ID,Real_Name) values (%s,%s,%s)'
query4 = 'insert into Apex_APAC_South (Team,ID,Real_Name) values (%s,%s,%s)'
query5 = 'insert into Apex_Team (Team) values (%s)'
query6 = 'insert into Apex_Player (ID,Real_Name) values (%s,%s)'
query7 = 'insert into Apex_Top20 (ID,Real_Name,Country,Born,Age,Team) values (%s,%s,%s,%s,%s,%s)'
query8 = 'insert into Apex_NearlyMatch (ID,Ranks,Matches) values (%s,%s,%s)'
query9 = 'insert into Apex_TeamOverall (Team,Totalwinnings) values (%s,%s)'
query10 = 'insert into Apex_PlayerOverall (ID,1st,2nd,3rd_4th,S_Tier,Earnings) values (%s,%s,%s,%s,%s,%s)'
query11 = 'insert into Apex_Youngest (ID,Age) values (%s,%s)'
query12 = 'insert into Apex_Oldest (ID,Age) values (%s,%s)'

def getExcel(query,sheet):
    for row in range(0,sheet.nrows):
        Team = sheet.cell(row,0).value
        ID = sheet.cell(row,1).value
        Real_Name = sheet.cell(row,2).value
        values =(Team,ID,Real_Name)
        cursor.execute(query,values)

def getExcelTeam(query,sheet):
    for row in range(0,sheet.nrows):
        Team = sheet.cell(row,0).value
        values =(Team)
        cursor.execute(query,values)

def getExcelPlayer(query,sheet):
    for row in range(0,sheet.nrows):
        ID = sheet.cell(row,0).value
        Real_Name = sheet.cell(row,1).value
        values =(ID,Real_Name)
        cursor.execute(query,values)

def getExcelTop20(query,sheet):
    for row in range(0,sheet.nrows):
        ID = sheet.cell(row,0).value
        Real_Name = sheet.cell(row,1).value
        Country = sheet.cell(row,2).value
        Born = (sheet.cell(row,3).value)
        Dt = xlrd.xldate_as_datetime(Born,0)
        Age = sheet.cell(row,4).value
        Team = sheet.cell(row,5).value
        values =(ID,Real_Name,Country,Dt,Age,Team)
        cursor.execute(query,values)

def getExcelNearlyMatch(query,sheet):
    for row in range(0,sheet.nrows):
        ID = sheet.cell(row,0).value
        Ranks = sheet.cell(row,1).value
        Matches = sheet.cell(row,2).value
        values =(ID,Ranks,Matches)
        cursor.execute(query,values)

def getExcelYearTeam(year,sheet):
    for row in range(5*(year-2019),5*(year-2019)+50):
        Team = sheet.cell(row,0).value
        _1st = sheet.cell(row,1).value
        _2nd = sheet.cell(row,2).value
        _3rd_4th = sheet.cell(row,3).value
        Totalwinnings = sheet.cell(row,4).value
        query = 'insert into Apex_Team'+str(year)+'(Team,1st,2nd,3rd_4th,Totalwinnings) values (%s,%s,%s,%s,%s)'
        values = (Team,_1st,_2nd,_3rd_4th,Totalwinnings)
        cursor.execute(query,values)

def getExcelYearPlayer(year,sheet):
    for row in range(5*(year-2019),5*(year-2019)+50):
        ID = sheet.cell(row,0).value
        _1st = sheet.cell(row,1).value
        _2nd = sheet.cell(row,2).value
        _3rd_4th = sheet.cell(row,3).value
        _S_Tier = sheet.cell(row,4).value
        Earnings = sheet.cell(row,5).value
        query = 'insert into Apex_Player'+str(year)+'(ID,1st,2nd,3rd_4th,S_Tier,Earnings) values (%s,%s,%s,%s,%s,%s)'
        values = (ID,_1st,_2nd,_3rd_4th,_S_Tier,Earnings)
        cursor.execute(query,values)

def getExcelTeamOverall(query,sheet):
    for row in range(1,sheet.nrows):
        Team = sheet.cell(row,0).value
        Totalwinnings = sheet.cell(row,1).value
        values =(Team,Totalwinnings)
        cursor.execute(query,values)

def getExcelPlayerOverall(query,sheet):
    for row in range(1,sheet.nrows):
        ID = sheet.cell(row,0).value
        _1st = sheet.cell(row,1).value
        _2nd = sheet.cell(row,2).value
        _3rd_4th = sheet.cell(row,3).value
        _S_Tier = sheet.cell(row,4).value
        Earnings = sheet.cell(row,5).value
        values = (ID,_1st,_2nd,_3rd_4th,_S_Tier,Earnings)
        cursor.execute(query,values)

def getExcelYoungest(query,sheet):
    for row in range(1,sheet.nrows):
        ID = sheet.cell(row,0).value
        Age = sheet.cell(row,1).value
        values = (ID,Age)
        cursor.execute(query,values)

def getExcelOldest(query,sheet):
    for row in range(1,sheet.nrows):
        ID = sheet.cell(row,0).value
        Age = sheet.cell(row,1).value
        values = (ID,Age)
        cursor.execute(query,values)

getExcel(query1,sheet1)        
getExcel(query2,sheet2)  
getExcel(query3,sheet3)  
getExcel(query4,sheet4)  
getExcelTeam(query5,sheet5) 
getExcelPlayer(query6,sheet6) 
getExcelTop20(query7,sheet7) 
getExcelNearlyMatch(query8,sheet8) 
for year in range(2019,2024):
    getExcelYearTeam(year,sheet9)
    getExcelYearPlayer(year,sheet10)
getExcelTeamOverall(query9,sheet11) 
getExcelPlayerOverall(query10,sheet12)
getExcelYoungest(query11,sheet13)
getExcelOldest(query12,sheet14)   
db.commit()
db.close()